Update patch set 6
Patch Set 6:

10-16 13:27:07.459 D/AndroidRuntime(14823): Shutting down VM
10-16 13:27:07.460 E/AndroidRuntime(14823): FATAL EXCEPTION: main
10-16 13:27:07.460 E/AndroidRuntime(14823): Process: com.android.phone, PID: 14823
10-16 13:27:07.460 E/AndroidRuntime(14823): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/ims/ImsReasonInfo;
10-16 13:27:07.460 E/AndroidRuntime(14823): 	at org.codeaurora.ims.ImsServiceSub$ImsServiceSubHandler.handleImsStateChanged(ImsServiceSub.java:1262)
10-16 13:27:07.460 E/AndroidRuntime(14823): 	at org.codeaurora.ims.ImsServiceSub$ImsServiceSubHandler.handleMessage(ImsServiceSub.java:1354)
10-16 13:27:07.460 E/AndroidRuntime(14823): 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-16 13:27:07.460 E/AndroidRuntime(14823): 	at android.os.Looper.loop(Looper.java:193)
10-16 13:27:07.460 E/AndroidRuntime(14823): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
10-16 13:27:07.460 E/AndroidRuntime(14823): 	at java.lang.reflect.Method.invoke(Native Method)
10-16 13:27:07.460 E/AndroidRuntime(14823): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
10-16 13:27:07.460 E/AndroidRuntime(14823): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-16 13:27:07.460 E/AndroidRuntime(14823): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.ims.ImsReasonInfo" on path: DexPathList[[zip file "/system/vendor/app/ims/ims.apk"],nativeLibraryDirectories=[/system/vendor/app/ims/lib/arm64, /system/vendor/app/ims/ims.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
10-16 13:27:07.460 E/AndroidRuntime(14823): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
10-16 13:27:07.460 E/AndroidRuntime(14823): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-16 13:27:07.460 E/AndroidRuntime(14823): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-16 13:27:07.460 E/AndroidRuntime(14823): 	... 8 more
10-16 13:27:07.463 I/QImsService(14823): ImsSenderRxr : isValid = true type = 2 status = 0 userdata = null[SUB0]
10-16 13:27:07.463 I/QImsService(14823): ImsSenderRxr :  networkMode = -1 status = 0 restrictCause = 0 registered = 2[SUB0]
10-16 13:27:07.463 I/QImsService(14823): ImsSenderRxr : isValid = true type = 11 status = 0 userdata = null[SUB0]
10-16 13:27:07.464 I/QImsService(14823): ImsSenderRxr :  networkMode = 14 status = 2 restrictCause = 0 registered = 1[SUB0]
10-16 13:27:07.464 I/QImsService(14823): ImsSenderRxr : [UNSL]< UNSOL_SRV_STATUS_UPDATE [org.codeaurora.ims.ServiceStatus@b05633e, org.codeaurora.ims.ServiceStatus@57c559f, org.codeaurora.ims.ServiceStatus@116ec, org.codeaurora.ims.ServiceStatus@bfadab5, org.codeaurora.ims.ServiceStatus@570754a][SUB0]
10-16 13:27:07.473 I/Process (14823): Sending signal. PID: 14823 SIG: 9
10-16 13:27:07.543 I/ServiceManager(348): service 'ims' died
10-16 13:27:07.544 I/ServiceManager(348): service 'qti.ims.ext' died
10-16 13:27:07.544 I/ServiceManager(348): service 'isub' died
10-16 13:27:07.544 I/ServiceManager(348): service 'phone' died
10-16 13:27:07.544 I/ServiceManager(348): service 'carrier_config' died
10-16 13:27:07.544 I/ServiceManager(348): service 'iphonesubinfo' died
10-16 13:27:07.544 I/ServiceManager(348): service 'isms' died
10-16 13:27:07.544 I/ServiceManager(348): service 'simphonebook' died
10-16 13:27:07.544 I/ServiceManager(348): service 'sip' died

Patch-set: 6
Reviewer: Gerrit User 16208 <16208@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=0